/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Config.connectionConfig;
import Config.userConfig;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;



/**
 *
 * @author faramadhan
 */
public class masterForm extends javax.swing.JFrame {

    /**
     * Creates new form masterForm
     */
    
    public String sessName;
    public masterForm() {
        initComponents();
        
        int totalDataGuru = Config.countData.getSumGuru();
        int totalDataSiswa = Config.countData.getSumSiswa();
        int totalDataTU = Config.countData.getSumTU();
        int totalDataKelas = Config.countData.getSumKelas();
        
        this.setExtendedState(this.getExtendedState() | MAXIMIZED_BOTH);
        getClock();
        
        lblSumTeacher.setText(Integer.toString(totalDataGuru));
        lblSumStudent.setText(Integer.toString(totalDataSiswa));
        lblSumTU.setText(Integer.toString(totalDataTU));
        lblSumClass.setText(Integer.toString(totalDataKelas));
        lblPagetitle.setText("Beranda");
    }
    
    public void viewUser(String name){
        lblUserName.setText(name);
         sessName = name;
    }
    
    public void getClock(){
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt){
                SimpleDateFormat tgl = new SimpleDateFormat("EEEE, dd-MMM-YYYY");
                String no1_jam = "";
                String no1_menit = "";
                String no1_detik = "";
                
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <= 9){
                    no1_jam = "0";
                }
                if(nilai_menit <= 9){
                    no1_menit = "0";
                }
                if(nilai_detik <= 9){
                    no1_detik = "0";
                }
                
                String jam = no1_jam + Integer.toString(nilai_jam);
                String menit = no1_menit + Integer.toString(nilai_menit);
                String detik = no1_detik + Integer.toString(nilai_detik);
                
                lblClock.setText(tgl.format(dt) + "   |   " + jam + " : " + menit + " : " + detik + " ");
            }
        };
        new javax.swing.Timer(1000, taskPerformer).start();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnTeacher = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblClock = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblSubTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pSumTeacher = new javax.swing.JPanel();
        iconSumTeacher = new javax.swing.JLabel();
        lblTitleSumTeacher = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblSumTeacher = new javax.swing.JLabel();
        pSumStudent = new javax.swing.JPanel();
        iconSumStudent = new javax.swing.JLabel();
        lblTitleSumStudent = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblSumStudent = new javax.swing.JLabel();
        pSumAdmin = new javax.swing.JPanel();
        iconSumTU = new javax.swing.JLabel();
        lblTitleSumTU = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblSumTU = new javax.swing.JLabel();
        pSumClass = new javax.swing.JPanel();
        iconSumClass = new javax.swing.JLabel();
        lblTitleSumClass = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lblSumClass = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblPagetitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" SIAKAD | SMP PGRI BOJONG");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1750, 900));
        setMaximumSize(new java.awt.Dimension(1750, 900));
        setMinimumSize(new java.awt.Dimension(1750, 900));
        setPreferredSize(new java.awt.Dimension(1750, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1750, 900));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 5, new java.awt.Color(255, 255, 255)));
        jPanel1.setMaximumSize(new java.awt.Dimension(250, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 900));

        jPanel5.setBackground(new java.awt.Color(164, 235, 243));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(255, 255, 255)));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-pgri.png"))); // NOI18N

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUserName)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(164, 235, 243));

        btnHome.setBackground(new java.awt.Color(164, 235, 243));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnHome.setForeground(new java.awt.Color(102, 102, 102));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/home.png"))); // NOI18N
        btnHome.setText("Beranda   ");
        btnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnHome.setIconTextGap(7);
        btnHome.setMargin(new java.awt.Insets(200, 14, 2, 14));
        btnHome.setMaximumSize(new java.awt.Dimension(139, 33));
        btnHome.setMinimumSize(new java.awt.Dimension(139, 33));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnTeacher.setBackground(new java.awt.Color(164, 235, 243));
        btnTeacher.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnTeacher.setForeground(new java.awt.Color(102, 102, 102));
        btnTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/teacher.png"))); // NOI18N
        btnTeacher.setText("Data Guru");
        btnTeacher.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTeacher.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnTeacher.setIconTextGap(7);
        btnTeacher.setMaximumSize(new java.awt.Dimension(139, 33));
        btnTeacher.setMinimumSize(new java.awt.Dimension(139, 33));
        btnTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherActionPerformed(evt);
            }
        });

        btnAdmin.setBackground(new java.awt.Color(164, 235, 243));
        btnAdmin.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(102, 102, 102));
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/admin.png"))); // NOI18N
        btnAdmin.setText("Tata Usaha");
        btnAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmin.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnAdmin.setIconTextGap(7);
        btnAdmin.setMaximumSize(new java.awt.Dimension(139, 33));
        btnAdmin.setMinimumSize(new java.awt.Dimension(139, 33));
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnSetting.setBackground(new java.awt.Color(164, 235, 243));
        btnSetting.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnSetting.setForeground(new java.awt.Color(102, 102, 102));
        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/setting.png"))); // NOI18N
        btnSetting.setText("Pengaturan");
        btnSetting.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSetting.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnSetting.setIconTextGap(7);
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(164, 235, 243));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(102, 102, 102));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/logout.png"))); // NOI18N
        btnLogout.setText("Logout        ");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnLogout.setIconTextGap(7);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnStudent.setBackground(new java.awt.Color(164, 235, 243));
        btnStudent.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnStudent.setForeground(new java.awt.Color(102, 102, 102));
        btnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/student.png"))); // NOI18N
        btnStudent.setText("Data Siswa");
        btnStudent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudent.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnStudent.setIconTextGap(7);
        btnStudent.setMaximumSize(new java.awt.Dimension(139, 33));
        btnStudent.setMinimumSize(new java.awt.Dimension(139, 33));
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClock.setText(" ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(lblClock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClock)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(170, 170, 170));

        lblSubTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblSubTitle.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitle.setText("SELAMAT DATANG DI SISTEM INFORMASI AKADEMIK");

        lblSubtitle.setBackground(new java.awt.Color(170, 170, 170));
        lblSubtitle.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitle.setText("SMP PGRI BOJONG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel3.setBackground(new java.awt.Color(204, 242, 244));
        jPanel3.setOpaque(false);

        pSumTeacher.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        iconSumTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon-guru.png"))); // NOI18N
        iconSumTeacher.setText("jLabel3");

        lblTitleSumTeacher.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTitleSumTeacher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleSumTeacher.setText("Jumlah Guru");

        lblSumTeacher.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblSumTeacher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSumTeacher.setText("0");

        javax.swing.GroupLayout pSumTeacherLayout = new javax.swing.GroupLayout(pSumTeacher);
        pSumTeacher.setLayout(pSumTeacherLayout);
        pSumTeacherLayout.setHorizontalGroup(
            pSumTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSumTeacherLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(iconSumTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addComponent(lblTitleSumTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3)
            .addComponent(lblSumTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pSumTeacherLayout.setVerticalGroup(
            pSumTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSumTeacherLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(iconSumTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleSumTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSumTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pSumStudent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        iconSumStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon-siswa.png"))); // NOI18N
        iconSumStudent.setText("jLabel3");

        lblTitleSumStudent.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTitleSumStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleSumStudent.setText("Jumlah Siswa");

        lblSumStudent.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblSumStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSumStudent.setText("0");

        javax.swing.GroupLayout pSumStudentLayout = new javax.swing.GroupLayout(pSumStudent);
        pSumStudent.setLayout(pSumStudentLayout);
        pSumStudentLayout.setHorizontalGroup(
            pSumStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSumStudentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(iconSumStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addComponent(lblTitleSumStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator4)
            .addComponent(lblSumStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pSumStudentLayout.setVerticalGroup(
            pSumStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSumStudentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(iconSumStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleSumStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSumStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pSumAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        iconSumTU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon-tu.png"))); // NOI18N
        iconSumTU.setText("jLabel3");

        lblTitleSumTU.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTitleSumTU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleSumTU.setText("Jumlah Tata Usaha");

        lblSumTU.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblSumTU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSumTU.setText("0");

        javax.swing.GroupLayout pSumAdminLayout = new javax.swing.GroupLayout(pSumAdmin);
        pSumAdmin.setLayout(pSumAdminLayout);
        pSumAdminLayout.setHorizontalGroup(
            pSumAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSumAdminLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(iconSumTU, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addComponent(lblTitleSumTU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator5)
            .addComponent(lblSumTU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pSumAdminLayout.setVerticalGroup(
            pSumAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSumAdminLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(iconSumTU, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleSumTU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSumTU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pSumClass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        iconSumClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon-class.png"))); // NOI18N
        iconSumClass.setText("jLabel3");

        lblTitleSumClass.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTitleSumClass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleSumClass.setText("Jumlah Kelas");

        lblSumClass.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblSumClass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSumClass.setText("0");

        javax.swing.GroupLayout pSumClassLayout = new javax.swing.GroupLayout(pSumClass);
        pSumClass.setLayout(pSumClassLayout);
        pSumClassLayout.setHorizontalGroup(
            pSumClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSumClassLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(iconSumClass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addComponent(lblTitleSumClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator7)
            .addComponent(lblSumClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pSumClassLayout.setVerticalGroup(
            pSumClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSumClassLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(iconSumClass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleSumClass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSumClass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(pSumTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(pSumStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(pSumAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(pSumClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pSumClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSumAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSumStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSumTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 242, 244));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(255, 255, 255)));

        lblPagetitle.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblPagetitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPagetitle.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblPagetitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPagetitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1768, 954));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherActionPerformed
        dataGuruForm dGF = new dataGuruForm();
        dGF.setVisible(true);
        dGF.viewUser(sessName);
        dispose();
    }//GEN-LAST:event_btnTeacherActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        dataTUForm dTU = new dataTUForm();
        dTU.setVisible(true);
        dTU.viewUser(sessName);
        dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        settingForm sF = new settingForm();
        sF.setVisible(true);
        sF.viewUser(sessName);
        dispose();
    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int yakinHapus = JOptionPane.showConfirmDialog(null, "Anda yakin?", "Logout", JOptionPane.YES_NO_OPTION);
        if(yakinHapus == JOptionPane.YES_OPTION){
            this.dispose();
            loginFrame lF = new loginFrame();
            lF.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        dataSiswaForm dMF = new dataSiswaForm();
        dMF.setVisible(true);
        dMF.viewUser(sessName);
        dispose();
    }//GEN-LAST:event_btnStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSetting;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnTeacher;
    private javax.swing.JLabel iconSumClass;
    private javax.swing.JLabel iconSumStudent;
    private javax.swing.JLabel iconSumTU;
    private javax.swing.JLabel iconSumTeacher;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPagetitle;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblSumClass;
    private javax.swing.JLabel lblSumStudent;
    private javax.swing.JLabel lblSumTU;
    private javax.swing.JLabel lblSumTeacher;
    private javax.swing.JLabel lblTitleSumClass;
    private javax.swing.JLabel lblTitleSumStudent;
    private javax.swing.JLabel lblTitleSumTU;
    private javax.swing.JLabel lblTitleSumTeacher;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pSumAdmin;
    private javax.swing.JPanel pSumClass;
    private javax.swing.JPanel pSumStudent;
    private javax.swing.JPanel pSumTeacher;
    // End of variables declaration//GEN-END:variables
    
    userConfig uc = new userConfig();
    
}
