/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Config.connectionConfig;
import Config.userConfig;
import Report.detailKelas;
import Report.detailMapel;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author faramadhan
 */
public class settingForm extends javax.swing.JFrame {

    /**
     * Creates new form masterForm
     */
    
    public String sessName;
    public settingForm() {
        initComponents();
            
        this.setExtendedState(this.getExtendedState() | MAXIMIZED_BOTH);
        
        getClock();
        pilihGuru();
        pilihGuru1();
        emptyField();
        showDataKelas();
        showDataMapel();
        showDataUser();
        lblPagetitle.setText("Beranda");
    }
    
    public void viewUser(String name){
        lblUserName.setText(name);
         sessName = name;
    }
    
    public void getClock(){
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt){
                SimpleDateFormat tgl = new SimpleDateFormat("EEEE, dd-MMM-YYYY");
                String no1_jam = "";
                String no1_menit = "";
                String no1_detik = "";
                
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <= 9){
                    no1_jam = "0";
                }
                if(nilai_menit <= 9){
                    no1_menit = "0";
                }
                if(nilai_detik <= 9){
                    no1_detik = "0";
                }
                
                String jam = no1_jam + Integer.toString(nilai_jam);
                String menit = no1_menit + Integer.toString(nilai_menit);
                String detik = no1_detik + Integer.toString(nilai_detik);
                
                lblClock.setText(tgl.format(dt) + "   |   " + jam + " : " + menit + " : " + detik + " ");
            }
        };
        new javax.swing.Timer(1000, taskPerformer).start();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnTeacher = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblClock = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblSubTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKelas = new javax.swing.JTextField();
        cmbWakel = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKelas = new javax.swing.JTable();
        btnDetail = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMapel = new javax.swing.JTextField();
        cmbTingkatKelas = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbGuruMapel = new javax.swing.JComboBox<>();
        btnHapus1 = new javax.swing.JButton();
        btnBatal1 = new javax.swing.JButton();
        btnDetail1 = new javax.swing.JButton();
        btnSimpan1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMapel = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblPagetitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" SIAKAD | SMP PGRI BOJONG");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1750, 900));
        setMinimumSize(new java.awt.Dimension(1750, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1750, 900));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 5, new java.awt.Color(255, 255, 255)));
        jPanel1.setMaximumSize(new java.awt.Dimension(250, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 900));

        jPanel5.setBackground(new java.awt.Color(164, 235, 243));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(255, 255, 255)));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-pgri.png"))); // NOI18N

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUserName)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(164, 235, 243));

        btnHome.setBackground(new java.awt.Color(164, 235, 243));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnHome.setForeground(new java.awt.Color(102, 102, 102));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/home.png"))); // NOI18N
        btnHome.setText("Beranda   ");
        btnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnHome.setIconTextGap(7);
        btnHome.setMargin(new java.awt.Insets(200, 14, 2, 14));
        btnHome.setMaximumSize(new java.awt.Dimension(139, 33));
        btnHome.setMinimumSize(new java.awt.Dimension(139, 33));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnTeacher.setBackground(new java.awt.Color(164, 235, 243));
        btnTeacher.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnTeacher.setForeground(new java.awt.Color(102, 102, 102));
        btnTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/teacher.png"))); // NOI18N
        btnTeacher.setText("Data Guru");
        btnTeacher.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTeacher.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnTeacher.setIconTextGap(7);
        btnTeacher.setMaximumSize(new java.awt.Dimension(139, 33));
        btnTeacher.setMinimumSize(new java.awt.Dimension(139, 33));
        btnTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherActionPerformed(evt);
            }
        });

        btnAdmin.setBackground(new java.awt.Color(164, 235, 243));
        btnAdmin.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(102, 102, 102));
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/admin.png"))); // NOI18N
        btnAdmin.setText("Tata Usaha");
        btnAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmin.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnAdmin.setIconTextGap(7);
        btnAdmin.setMaximumSize(new java.awt.Dimension(139, 33));
        btnAdmin.setMinimumSize(new java.awt.Dimension(139, 33));
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnSetting.setBackground(new java.awt.Color(164, 235, 243));
        btnSetting.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnSetting.setForeground(new java.awt.Color(102, 102, 102));
        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/setting.png"))); // NOI18N
        btnSetting.setText("Pengaturan");
        btnSetting.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSetting.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnSetting.setIconTextGap(7);
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(164, 235, 243));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(102, 102, 102));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/logout.png"))); // NOI18N
        btnLogout.setText("Logout        ");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnLogout.setIconTextGap(7);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnStudent.setBackground(new java.awt.Color(164, 235, 243));
        btnStudent.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnStudent.setForeground(new java.awt.Color(102, 102, 102));
        btnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/student.png"))); // NOI18N
        btnStudent.setText("Data Siswa");
        btnStudent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudent.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnStudent.setIconTextGap(7);
        btnStudent.setMaximumSize(new java.awt.Dimension(139, 33));
        btnStudent.setMinimumSize(new java.awt.Dimension(139, 33));
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClock.setText(" ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(lblClock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClock)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(170, 170, 170));

        lblSubTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblSubTitle.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitle.setText("SELAMAT DATANG DI SISTEM INFORMASI AKADEMIK");

        lblSubtitle.setBackground(new java.awt.Color(170, 170, 170));
        lblSubtitle.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitle.setText("SMP PGRI BOJONG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel3.setBackground(new java.awt.Color(204, 242, 244));
        jPanel3.setOpaque(false);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel8.setMaximumSize(new java.awt.Dimension(740, 700));
        jPanel8.setMinimumSize(new java.awt.Dimension(740, 700));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA KELAS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Kelas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Wali Kelas");

        txtKelas.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        cmbWakel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cmbWakel.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbWakelPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKelas);

        btnDetail.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDetail.setText("Detail");
        btnDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbWakel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 145, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cmbWakel))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel9.setMaximumSize(new java.awt.Dimension(740, 700));
        jPanel9.setMinimumSize(new java.awt.Dimension(740, 700));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATA MATA PELAJARAN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Kelas");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Mata Pelajaran");

        txtMapel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        cmbTingkatKelas.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cmbTingkatKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Kelas 7", "Kelas 8", "Kelas 9" }));
        cmbTingkatKelas.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbTingkatKelasPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Guru Mapel");

        cmbGuruMapel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cmbGuruMapel.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbGuruMapelPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        btnHapus1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnHapus1.setText("Hapus");
        btnHapus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus1ActionPerformed(evt);
            }
        });

        btnBatal1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnBatal1.setText("Batal");
        btnBatal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal1ActionPerformed(evt);
            }
        });

        btnDetail1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDetail1.setText("Detail");
        btnDetail1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetail1ActionPerformed(evt);
            }
        });

        btnSimpan1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSimpan1.setText("Simpan");
        btnSimpan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });

        tblMapel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMapelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMapel);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addComponent(jSeparator3)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbGuruMapel, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTingkatKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMapel)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbTingkatKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGuruMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Kelas & Mapel", jPanel7);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DATA USER");

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblUser);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1499, Short.MAX_VALUE)
            .addComponent(jSeparator4)
            .addComponent(jScrollPane3)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("User", jPanel10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jPanel4.setBackground(new java.awt.Color(204, 242, 244));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(255, 255, 255)));

        lblPagetitle.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblPagetitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPagetitle.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblPagetitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPagetitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1768, 954));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        masterForm mF = new masterForm();
        mF.setVisible(true);
        mF.viewUser(sessName);
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherActionPerformed
        dataGuruForm dGF = new dataGuruForm();
        dGF.setVisible(true);
        dGF.viewUser(sessName);
        dispose();
    }//GEN-LAST:event_btnTeacherActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        dataTUForm dTU = new dataTUForm();
        dTU.setVisible(true);
        dTU.viewUser(sessName);
        dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        
    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int yakinHapus = JOptionPane.showConfirmDialog(null, "Anda yakin?", "Logout", JOptionPane.YES_NO_OPTION);
        if(yakinHapus == JOptionPane.YES_OPTION){
            this.dispose();
            loginFrame lF = new loginFrame();
            lF.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        dataSiswaForm dMF = new dataSiswaForm();
        dMF.setVisible(true);
        dMF.viewUser(sessName);
        dispose();
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if(txtKelas.getText().isEmpty() || cmbWakel.getSelectedItem().toString().equals("Pilih")){
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong", "Pesan", JOptionPane.WARNING_MESSAGE);
        } else {
            if(idKelas == null){
                try {                    
                    String sql_insert = "INSERT INTO tbl_kelas (nama_kelas, id_guru) VALUES (?,?)";
                    Connection conn = connectionConfig.configDB();
                    PreparedStatement pst = conn.prepareStatement(sql_insert);
                    
                    pst.setString(1, txtKelas.getText());
                    pst.setString(2, idGuru);
                    
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Berhasil menambahkan data kelas", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                    showDataKelas();
                    emptyField();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal menambahkan data kelas: "+e.getMessage());
                }
            } else {
                try {
                    String sql_update = "UPDATE tbl_kelas SET nama_kelas = ?, id_guru = ? WHERE id_kelas = ?";
                    Connection conn = connectionConfig.configDB();
                    PreparedStatement pst = conn.prepareStatement(sql_update);
                    
                    pst.setString(1, txtKelas.getText());
                    pst.setString(2, idGuru);
                    pst.setString(3, idKelas);
                    
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Berhasil mengubah data kelas", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                    showDataKelas();
                    emptyField();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Data gagal diubah, error: \n" + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cmbWakelPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbWakelPopupMenuWillBecomeInvisible
        String pilihWakel = cmbWakel.getSelectedItem().toString();
        String sql_pilih_nama_guru = "SELECT * FROM tbl_guru WHERE nama = '"+pilihWakel+"'";
        try {
            Connection conn = connectionConfig.configDB();
            Statement stm = conn.createStatement();
            ResultSet rst = stm.executeQuery(sql_pilih_nama_guru);
            
            while(rst.next()){
                idGuru = rst.getString("id_guru");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cmbWakelPopupMenuWillBecomeInvisible

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        emptyField();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tblKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKelasMouseClicked
        int row = tblKelas.rowAtPoint(evt.getPoint());
        String id_kelas = tblKelas.getValueAt(row, 1).toString();
        
        try {
            String sql_select_id = "SELECT * FROM tbl_kelas INNER JOIN tbl_guru ON tbl_kelas.id_guru = tbl_guru.id_guru WHERE id_kelas = '"+id_kelas+"'";
            
            Connection conn = connectionConfig.configDB();
            Statement stm = conn.createStatement();
            ResultSet rst = stm.executeQuery(sql_select_id);
            
            while(rst.next()){
                idKelas = rst.getString("id_kelas");
                txtKelas.setText(rst.getString("nama_kelas"));
                cmbWakel.setSelectedItem(rst.getString("nama"));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Memuat Data: \n" + e.getMessage());
        }
    }//GEN-LAST:event_tblKelasMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if(txtKelas.getText().isEmpty() || cmbWakel.getSelectedItem().toString().equals("Pilih")){
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu", "Pesan", JOptionPane.WARNING_MESSAGE);
        } else {
            int yakinHapus = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data " + txtKelas.getText() + "?", "Hapus Data", JOptionPane.YES_NO_OPTION);
            if(yakinHapus == JOptionPane.YES_OPTION){
                try{
                    String sql_delete = "DELETE FROM tbl_kelas WHERE id_kelas = '" + idKelas + "'";
                    Connection conn = connectionConfig.configDB();
                    PreparedStatement pst = conn.prepareStatement(sql_delete);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Berhasil menghapus data kelas", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                } catch (HeadlessException | SQLException e){
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
                showDataKelas();
                emptyField();
            } else {
                showDataKelas();
                emptyField();
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void cmbTingkatKelasPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbTingkatKelasPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTingkatKelasPopupMenuWillBecomeInvisible

    private void cmbGuruMapelPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbGuruMapelPopupMenuWillBecomeInvisible
        String pilihGuruMapel = cmbGuruMapel.getSelectedItem().toString();
        String sql_pilih_nama_guru = "SELECT * FROM tbl_guru WHERE nama = '"+pilihGuruMapel+"'";
        try {
            Connection conn = connectionConfig.configDB();
            Statement stm = conn.createStatement();
            ResultSet rst = stm.executeQuery(sql_pilih_nama_guru);
            
            while(rst.next()){
                idGuru = rst.getString("id_guru");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cmbGuruMapelPopupMenuWillBecomeInvisible

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        detailKelas dKelas = new detailKelas();
        dKelas.setVisible(true);
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
        if(txtMapel.getText().isEmpty() || cmbTingkatKelas.getSelectedItem().toString().equals("Pilih") || cmbGuruMapel.getSelectedItem().toString().equals("Pili")){
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu", "Pesan", JOptionPane.WARNING_MESSAGE);
        } else {
            int yakinHapus = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data " + txtMapel.getText() + "?", "Hapus Data", JOptionPane.YES_NO_OPTION);
            if(yakinHapus == JOptionPane.YES_OPTION){
                try{
                    String sql_delete = "DELETE FROM tbl_mapel WHERE id_mapel = '" + idMapel + "'";
                    Connection conn = connectionConfig.configDB();
                    PreparedStatement pst = conn.prepareStatement(sql_delete);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Berhasil menghapus data mapel", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                } catch (HeadlessException | SQLException e){
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
                showDataMapel();
                emptyFieldMapel();
            } else {
                showDataMapel();
                emptyFieldMapel();
            }
        }
    }//GEN-LAST:event_btnHapus1ActionPerformed

    private void btnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal1ActionPerformed
        emptyFieldMapel();
    }//GEN-LAST:event_btnBatal1ActionPerformed

    private void btnDetail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetail1ActionPerformed
        detailMapel dMapel = new detailMapel();
        dMapel.setVisible(true);
    }//GEN-LAST:event_btnDetail1ActionPerformed

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
        if(txtMapel.getText().isEmpty() || cmbTingkatKelas.getSelectedItem().toString().equals("Pilih") || cmbGuruMapel.getSelectedItem().toString().equals("Pili")){
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong", "Pesan", JOptionPane.WARNING_MESSAGE);
        } else {
            if(idMapel == null){
                try {                    
                    String sql_insert = "INSERT INTO tbl_mapel (mapel, tingkat_kelas, id_guru) VALUES (?,?,?)";
                    Connection conn = connectionConfig.configDB();
                    PreparedStatement pst = conn.prepareStatement(sql_insert);
                    
                    pst.setString(1, txtMapel.getText());
                    pst.setString(2, cmbTingkatKelas.getSelectedItem().toString());
                    pst.setString(3, idGuru);
                    
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Berhasil menambahkan data mapel", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                    showDataMapel();
                    emptyFieldMapel();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal menambahkan data mapel: "+e.getMessage());
                }
            } else {
                try {
                    String sql_update = "UPDATE tbl_mapel SET mapel = ?, tingkat_kelas = ?, id_guru = ? WHERE id_mapel = ?";
                    Connection conn = connectionConfig.configDB();
                    PreparedStatement pst = conn.prepareStatement(sql_update);
                    
                    pst.setString(1, txtMapel.getText());
                    pst.setString(2, cmbTingkatKelas.getSelectedItem().toString());
                    pst.setString(3, idGuru);
                    pst.setString(4, idMapel);
                    
                    
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Berhasil mengubah data mapel", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                    showDataMapel();
                    emptyField();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Data gagal diubah, error: \n" + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void tblMapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMapelMouseClicked
        int row = tblMapel.rowAtPoint(evt.getPoint());
        String id_mapel = tblMapel.getValueAt(row, 1).toString();
        
        try {
            String sql_select_id = "SELECT * FROM tbl_mapel INNER JOIN tbl_guru ON tbl_mapel.id_guru = tbl_guru.id_guru WHERE id_mapel = '"+id_mapel+"'";
            
            Connection conn = connectionConfig.configDB();
            Statement stm = conn.createStatement();
            ResultSet rst = stm.executeQuery(sql_select_id);
            
            while(rst.next()){
                idMapel = rst.getString("id_mapel");
                txtMapel.setText(rst.getString("mapel"));
                cmbTingkatKelas.setSelectedItem(rst.getString("tingkat_kelas"));
                cmbGuruMapel.setSelectedItem(rst.getString("nama"));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Memuat Data: \n" + e.getMessage());
        }
    }//GEN-LAST:event_tblMapelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatal1;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnDetail1;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSetting;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpan1;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnTeacher;
    private javax.swing.JComboBox<String> cmbGuruMapel;
    private javax.swing.JComboBox<String> cmbTingkatKelas;
    private javax.swing.JComboBox<String> cmbWakel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPagetitle;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tblKelas;
    private javax.swing.JTable tblMapel;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtMapel;
    // End of variables declaration//GEN-END:variables
    
    userConfig uc = new userConfig();
    
    private String idGuru;
    private String idKelas;
    private String idMapel;
    
    private void pilihGuru(){
        try {
            String sql_pilih_guru = "SELECT * FROM tbl_guru ORDER BY nama ASC";
            Connection conn = connectionConfig.configDB();
            Statement pst = conn.createStatement();
            ResultSet rst = pst.executeQuery(sql_pilih_guru);
            
            cmbWakel.addItem("Pilih");
            while(rst.next()){
                cmbWakel.addItem(rst.getString("nama"));
            }
            rst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan data: "+e.getMessage());
        }
    }
    
    private void pilihGuru1(){
        try {
            String sql_pilih_guru = "SELECT * FROM tbl_guru ORDER BY nama ASC";
            Connection conn = connectionConfig.configDB();
            Statement pst = conn.createStatement();
            ResultSet rst = pst.executeQuery(sql_pilih_guru);
            
            cmbGuruMapel.addItem("Pilih");
            while(rst.next()){
                cmbGuruMapel.addItem(rst.getString("nama"));
            }
            rst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan data: "+e.getMessage());
        }
    }
    
    private void emptyField(){
        idKelas = null;
        txtKelas.setText(null);
        cmbWakel.setSelectedIndex(0);
    }
    
    private void emptyFieldMapel(){
        idMapel = null;
        txtMapel.setText(null);
        cmbTingkatKelas.setSelectedIndex(0);
        cmbGuruMapel.setSelectedIndex(0);
    }
    
    private void showDataKelas() {
        DefaultTableModel modelKelas = new DefaultTableModel();
        modelKelas.addColumn("No");
        modelKelas.addColumn("ID Kelas");
        modelKelas.addColumn("Nama Kelas");
        modelKelas.addColumn("Wali Kelas");
        
        try {
            int no = 1;
            
            String sql_select_all = "SELECT tbl_kelas.id_kelas, tbl_kelas.nama_kelas, tbl_guru.nama FROM tbl_kelas INNER JOIN tbl_guru ON tbl_kelas.id_guru = tbl_guru.id_guru";
            
            Connection conn = (Connection) connectionConfig.configDB();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql_select_all);
            
            while (rs.next()){
                modelKelas.addRow(new Object[] {
                    no++,
                    rs.getString("id_kelas"),
                    rs.getString("nama_kelas"),
                    rs.getString("nama")
                });
                ;
            }
            
            tblKelas.setModel(modelKelas);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal Memuat Data: \n" + e.getMessage());
        }
    }
    
    private void showDataMapel() {
        DefaultTableModel modelMapel = new DefaultTableModel();
        modelMapel.addColumn("No");
        modelMapel.addColumn("ID Mapel");
        modelMapel.addColumn("Mata Pelajaran");
        modelMapel.addColumn("Tingkat Kelas");
        modelMapel.addColumn("Guru Mapel");
        
        try {
            int no = 1;
            
            String sql_select_all = "SELECT * FROM tbl_mapel INNER JOIN tbl_guru ON tbl_mapel.id_guru = tbl_guru.id_guru ORDER BY tingkat_kelas ASC";
            
            Connection conn = connectionConfig.configDB();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql_select_all);
            
            while (rs.next()){
                modelMapel.addRow(new Object[] {
                    no++,
                    rs.getString("id_mapel"),
                    rs.getString("mapel"),
                    rs.getString("tingkat_kelas"),
                    rs.getString("nama")
                });
                ;
            }
            
            tblMapel.setModel(modelMapel);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal Memuat Data: \n" + e.getMessage());
        }
    }
    
    private void showDataUser() {
        DefaultTableModel modelUser = new DefaultTableModel();
        modelUser.addColumn("No");
        modelUser.addColumn("Nama");
        modelUser.addColumn("Username");
        modelUser.addColumn("Hak Akses");
        
        try {
            int no = 1;
            
            String sql_select_all = "SELECT * FROM tbl_user ORDER BY name ASC";
            
            Connection conn = (Connection) connectionConfig.configDB();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql_select_all);
            
            while (rs.next()){
                modelUser.addRow(new Object[] {
                    no++,
                    rs.getString("name"),
                    rs.getString("username"),
                    rs.getString("access")
                });
                ;
            }
            
            tblUser.setModel(modelUser);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal Memuat Data: \n" + e.getMessage());
        }
    }
}
